### ISSUE TITLE
Headless UI: Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by agracia-foticos** [johannschopplich/nuxt-vitalizer#3]
### Environment

https://stackblitz.com/edit/nuxt-starter-zc7r2b

### Reproduction

Open the url and Hydration completed but contains mismatches. raises in console

### Describe the bug

Open the url and Hydration completed but contains mismatches. raises in console.

Check https://github.com/P4sca1/nuxt-headlessui/issues/49

**Comment by agracia-foticos** [comment]
Any advance?

**Comment by johannschopplich** [comment]
I'm not sure it's a good idea to wrap third party code in `DelayHydration` because it may have custom logic that is required on the client for interactivity, especially headless UI. Having said that, I need to investigate the issue at hand. At least Nuxt shouldn't throw an hydration error when re-using the server rendered HTML.

A note on usage: If you're using `DelayHydration`, you have to use the `Lazy` version of a given component, like `LazyHeadlessPopover`. Otherwise you will lose the benefit of lazy hydration because the code of the component will be fetched.

**Comment by agracia-foticos** [comment]
> I'm not sure it's a good idea to wrap third party code in `DelayHydration` because it may have custom logic that is required on the client for interactivity, especially headless UI. Having said that, I need to investigate the issue at hand. At least Nuxt shouldn't throw an hydration error when re-using the server rendered HTML.
> 
> A note on usage: If you're using `DelayHydration`, you have to use the `Lazy` version of a given component, like `LazyHeadlessPopover`. Otherwise you will lose the benefit of lazy hydration because the code of the component will be fetched.

But the creator of nuxt headless ui tells me that not use Lazy with Nuxt headless ui
https://github.com/P4sca1/nuxt-headlessui/issues/49

Ensure you are using a signle root element. See https://github.com/nuxt/nuxt/pull/26315.
Using LazyHeadlessPopover does not work. Use HeadlessPopover instead. This might apply to other components too. You will get a hydration missmatch where the id often looks similar, but uses a _ instead of a - for example. See https://github.com/nuxt/nuxt/issues/27378.

**Comment by johannschopplich** [comment]
Ah OK, I see. Seems like Headless UI requires execution in the browser to set the correct `id` which is server-side generated and provided in the client with `useId`. This is not an issue with the Nuxt Vitalizer module.

I don't recommend using `DelayHydration` in conjunction with Headless UI. If you can't lazily fetch the component, then it doesn't make sense to delay the hydration. If the component's code is fetched in the browser, I highly recommend to execute it, instead of trying to delay its hydration. Otherwise it feels kinda like an anti-pattern.

**Comment by agracia-foticos** [comment]
@johannschopplich there is any way to skip delayhidration inside? Something like this

`<DelayHydration>
<Skip>
<HeadlessUiComponent />
</Skip>
</DelayHydration>`
